services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: coding_tracker
    ports:
      - "5433:5432"  # 5432 на 5433
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: